import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import Toast from '../../components/common/Toast';
import LoadingSpinner from '../../components/common/LoadingSpinner';

const accountTypes = [
  { id: 'CUSTOMER', label: 'Personal', desc: 'Send money, pay bills, cash out' },
  { id: 'AGENT', label: 'Agent', desc: 'Cash in/out point for customers' },
  { id: 'MERCHANT', label: 'Merchant', desc: 'Accept payments from customers' },
];

export default function RegisterPage() {
  const [form, setForm] = useState({
    phoneNumber: '', fullName: '', securityPin: '', confirmPin: '',
    accountType: 'CUSTOMER',
    // Agent fields (code is auto-generated by system)
    shopName: '', shopAddress: '',
    // Merchant fields (code is auto-generated by system)
    businessName: '', businessType: '',
  });
  const [toast, setToast] = useState({ message: '', type: 'error' });
  const { register, loading } = useAuth();
  const navigate = useNavigate();

  const updateField = (field) => (e) => {
    let value = e.target.value;
    if (field === 'phoneNumber') value = value.replace(/\D/g, '').slice(0, 11);
    if (field === 'securityPin' || field === 'confirmPin') value = value.replace(/\D/g, '').slice(0, 5);
    setForm((prev) => ({ ...prev, [field]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!/^01[3-9][0-9]{8}$/.test(form.phoneNumber)) {
      return setToast({ message: 'Enter a valid Bangladeshi phone number', type: 'error' });
    }
    if (form.fullName.trim().length < 2) {
      return setToast({ message: 'Name must be at least 2 characters', type: 'error' });
    }
    if (!/^\d{5}$/.test(form.securityPin)) {
      return setToast({ message: 'PIN must be exactly 5 digits', type: 'error' });
    }
    if (form.securityPin !== form.confirmPin) {
      return setToast({ message: 'PINs do not match', type: 'error' });
    }

    // Validate role-specific fields
    if (form.accountType === 'AGENT') {
      if (!form.shopName.trim()) return setToast({ message: 'Shop name is required', type: 'error' });
    }
    if (form.accountType === 'MERCHANT') {
      if (!form.businessName.trim()) return setToast({ message: 'Business name is required', type: 'error' });
    }

    // Build the payload (agent/merchant codes are auto-generated by the system)
    const payload = {
      phoneNumber: form.phoneNumber,
      fullName: form.fullName.trim(),
      securityPin: form.securityPin,
      accountType: form.accountType,
    };
    if (form.accountType === 'AGENT') {
      payload.shopName = form.shopName.trim();
      payload.shopAddress = form.shopAddress.trim() || undefined;
    }
    if (form.accountType === 'MERCHANT') {
      payload.businessName = form.businessName.trim();
      payload.businessType = form.businessType.trim() || undefined;
    }

    const result = await register(payload);
    if (result.success) {
      const msg = form.accountType !== 'CUSTOMER'
        ? 'Registration successful! Your account is pending admin verification.'
        : 'Registration successful!';
      setToast({ message: msg, type: 'success' });
      setTimeout(() => {
        navigate('/verify-otp', {
          state: { phoneNumber: form.phoneNumber, otp: result.data.otp },
        });
      }, 1000);
    } else {
      setToast({ message: result.message, type: 'error' });
    }
  };

  return (
    <div className="flex min-h-dvh flex-col items-center justify-center bg-gradient-to-b from-primary-600 to-primary-800 px-4 py-8">
      <Toast message={toast.message} type={toast.type} onClose={() => setToast({ message: '', type: 'error' })} />

      <div className="w-full max-w-sm">
        <div className="mb-6 text-center">
          <h1 className="text-2xl font-bold text-white">Create Account</h1>
          <p className="mt-1 text-sm text-primary-200">Join TekaPakhi today</p>
        </div>

        <div className="rounded-2xl bg-white p-6 shadow-xl">
          <form onSubmit={handleSubmit} className="space-y-4">

            {/* Account Type Selector */}
            <div>
              <label className="mb-2 block text-sm font-medium text-gray-700">Account Type</label>
              <div className="grid grid-cols-3 gap-2">
                {accountTypes.map((type) => (
                  <button
                    key={type.id}
                    type="button"
                    onClick={() => setForm((prev) => ({ ...prev, accountType: type.id }))}
                    className={`rounded-lg border-2 px-2 py-2.5 text-center transition-colors
                      ${form.accountType === type.id
                        ? 'border-primary-500 bg-primary-50 text-primary-700'
                        : 'border-gray-200 bg-white text-gray-600 hover:border-gray-300'
                      }`}
                  >
                    <p className="text-xs font-semibold">{type.label}</p>
                    <p className="mt-0.5 text-[9px] leading-tight text-gray-400">{type.desc}</p>
                  </button>
                ))}
              </div>
            </div>

            {/* Common Fields */}
            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700">Full Name</label>
              <input
                type="text"
                value={form.fullName}
                onChange={updateField('fullName')}
                placeholder="Enter your full name"
                className="w-full rounded-lg border border-gray-300 px-4 py-3 text-sm focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-200"
                maxLength={100}
              />
            </div>

            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700">Phone Number</label>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm text-gray-400">+88</span>
                <input
                  type="tel"
                  value={form.phoneNumber}
                  onChange={updateField('phoneNumber')}
                  placeholder="01XXXXXXXXX"
                  className="w-full rounded-lg border border-gray-300 py-3 pl-12 pr-4 text-sm focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-200"
                  maxLength={11}
                />
              </div>
            </div>

            {/* Agent-specific Fields */}
            {form.accountType === 'AGENT' && (
              <div className="space-y-3 rounded-lg border border-blue-100 bg-blue-50/50 p-3">
                <p className="text-xs font-semibold text-blue-700">Agent Details</p>
                <p className="text-[10px] text-blue-500">Your Agent Code will be auto-generated after registration.</p>
                <input
                  type="text"
                  value={form.shopName}
                  onChange={updateField('shopName')}
                  placeholder="Shop Name *"
                  className="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm focus:border-primary-500 focus:outline-none"
                  maxLength={100}
                />
                <input
                  type="text"
                  value={form.shopAddress}
                  onChange={updateField('shopAddress')}
                  placeholder="Shop Address (optional)"
                  className="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm focus:border-primary-500 focus:outline-none"
                  maxLength={500}
                />
              </div>
            )}

            {/* Merchant-specific Fields */}
            {form.accountType === 'MERCHANT' && (
              <div className="space-y-3 rounded-lg border border-purple-100 bg-purple-50/50 p-3">
                <p className="text-xs font-semibold text-purple-700">Merchant Details</p>
                <p className="text-[10px] text-purple-500">Your Merchant Code will be auto-generated after registration.</p>
                <input
                  type="text"
                  value={form.businessName}
                  onChange={updateField('businessName')}
                  placeholder="Business Name *"
                  className="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm focus:border-primary-500 focus:outline-none"
                  maxLength={100}
                />
                <input
                  type="text"
                  value={form.businessType}
                  onChange={updateField('businessType')}
                  placeholder="Business Type (optional, e.g., Retail)"
                  className="w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm focus:border-primary-500 focus:outline-none"
                  maxLength={50}
                />
              </div>
            )}

            {form.accountType !== 'CUSTOMER' && (
              <p className="rounded-lg bg-yellow-50 px-3 py-2 text-[11px] text-yellow-700">
                Agent and Merchant accounts require admin verification before you can perform transactions.
              </p>
            )}

            {/* PIN Fields */}
            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700">Set PIN (5 digits)</label>
              <input
                type="password"
                value={form.securityPin}
                onChange={updateField('securityPin')}
                placeholder="Enter 5-digit PIN"
                inputMode="numeric"
                className="w-full rounded-lg border border-gray-300 px-4 py-3 text-sm focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-200"
                maxLength={5}
              />
            </div>

            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700">Confirm PIN</label>
              <input
                type="password"
                value={form.confirmPin}
                onChange={updateField('confirmPin')}
                placeholder="Re-enter your PIN"
                inputMode="numeric"
                className="w-full rounded-lg border border-gray-300 px-4 py-3 text-sm focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-200"
                maxLength={5}
              />
            </div>

            <button
              type="submit"
              disabled={loading}
              className="flex w-full items-center justify-center rounded-lg bg-primary-600 py-3 text-sm font-semibold text-white transition-colors hover:bg-primary-700 disabled:opacity-50"
            >
              {loading ? <LoadingSpinner size="sm" /> : 'Create Account'}
            </button>
          </form>
        </div>

        <p className="mt-6 text-center text-sm text-primary-200">
          Already have an account?{' '}
          <Link to="/login" className="font-semibold text-white hover:underline">
            Login
          </Link>
        </p>
      </div>
    </div>
  );
}
