const PROFILE_TYPES = {
  CUSTOMER: 1,
  AGENT: 2,
  MERCHANT: 3,
  DISTRIBUTOR: 4,
  BILLER: 5,
  SYSTEM: 6,
};

const PROFILE_TYPE_NAMES = {
  1: 'CUSTOMER',
  2: 'AGENT',
  3: 'MERCHANT',
  4: 'DISTRIBUTOR',
  5: 'BILLER',
  6: 'SYSTEM',
};

const PROFILE_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING_KYC: 'PENDING_KYC',
  BLOCKED: 'BLOCKED',
};

const TRANSACTION_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REVERSED: 'REVERSED',
};

const OTP_PURPOSE = {
  VERIFY_PHONE: 'VERIFY_PHONE',
  RESET_PIN: 'RESET_PIN',
};

module.exports = {
  PROFILE_TYPES,
  PROFILE_TYPE_NAMES,
  PROFILE_STATUS,
  TRANSACTION_STATUS,
  OTP_PURPOSE,
};
