CREATE TABLE IF NOT EXISTS locations (
    location_id SERIAL PRIMARY KEY,
    district VARCHAR(100) NOT NULL,
    area VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(district, area)
);

CREATE INDEX IF NOT EXISTS idx_locations_district ON locations(district);
CREATE INDEX IF NOT EXISTS idx_locations_area ON locations(area);

-- Seed data
INSERT INTO tp.locations (district, area)
VALUES 
('Barguna', 'Amtali'),
('Barguna', 'Bamna'),
('Barguna', 'Barguna Sadar'),
('Barguna', 'Betagi'),
('Barguna', 'Patharghata'),
('Barguna', 'Taltali'),
('Barishal', 'Muladi'),
('Barishal', 'Babuganj'),
('Barishal', 'Agailjhara'),
('Barishal', 'Barisal Sadar'),
('Barishal', 'Bakerganj'),
('Barishal', 'Banaripara'),
('Barishal', 'Gaurnadi'),
('Barishal', 'Hizla'),
('Barishal', 'Mehendiganj'),
('Barishal', 'Wazirpur'),
('Bhola', 'Bhola Sadar'),
('Bhola', 'Burhanuddin'),
('Bhola', 'Char Fasson'),
('Bhola', 'Daulatkhan'),
('Bhola', 'Lalmohan'),
('Bhola', 'Manpura'),
('Bhola', 'Tazumuddin'),
('Jhalokati', 'Jhalokati Sadar'),
('Jhalokati', 'Kathalia'),
('Jhalokati', 'Nalchity'),
('Jhalokati', 'Rajapur'),
('Patuakhali', 'Bauphal'),
('Patuakhali', 'Dashmina'),
('Patuakhali', 'Galachipa'),
('Patuakhali', 'Kalapara'),
('Patuakhali', 'Mirzaganj'),
('Patuakhali', 'Patuakhali Sadar'),
('Patuakhali', 'Dumki'),
('Patuakhali', 'Rangabali'),
('Pirojpur', 'Bhandaria'),
('Pirojpur', 'Kaukhali'),
('Pirojpur', 'Mathbaria'),
('Pirojpur', 'Nazirpur'),
('Pirojpur', 'Nesarabad'),
('Pirojpur', 'Pirojpur Sadar'),
('Pirojpur', 'Zianagar'),
('Bandarban', 'Bandarban Sadar'),
('Bandarban', 'Thanchi'),
('Bandarban', 'Lama'),
('Bandarban', 'Naikhongchhari'),
('Bandarban', 'Ali kadam'),
('Bandarban', 'Rowangchhari'),
('Bandarban', 'Ruma'),
('Brahmanbaria', 'Brahmanbaria Sadar'),
('Brahmanbaria', 'Ashuganj'),
('Brahmanbaria', 'Nasirnagar'),
('Brahmanbaria', 'Nabinagar'),
('Brahmanbaria', 'Sarail'),
('Brahmanbaria', 'Shahbazpur Town'),
('Brahmanbaria', 'Kasba'),
('Brahmanbaria', 'Akhaura'),
('Brahmanbaria', 'Bancharampur'),
('Brahmanbaria', 'Bijoynagar'),
('Chandpur', 'Chandpur Sadar'),
('Chandpur', 'Faridganj'),
('Chandpur', 'Haimchar'),
('Chandpur', 'Haziganj'),
('Chandpur', 'Kachua'),
('Chandpur', 'Matlab Uttar'),
('Chandpur', 'Matlab Dakkhin'),
('Chandpur', 'Shahrasti'),
('Chattogram', 'Anwara'),
('Chattogram', 'Banshkhali'),
('Chattogram', 'Boalkhali'),
('Chattogram', 'Chandanaish'),
('Chattogram', 'Fatikchhari'),
('Chattogram', 'Hathazari'),
('Chattogram', 'Lohagara'),
('Chattogram', 'Mirsharai'),
('Chattogram', 'Patiya'),
('Chattogram', 'Rangunia'),
('Chattogram', 'Raozan'),
('Chattogram', 'Sandwip'),
('Chattogram', 'Satkania'),
('Chattogram', 'Sitakunda'),
('Cumilla', 'Barura'),
('Cumilla', 'Brahmanpara'),
('Cumilla', 'Burichong'),
('Cumilla', 'Chandina'),
('Cumilla', 'Chauddagram'),
('Cumilla', 'Daudkandi'),
('Cumilla', 'Debidwar'),
('Cumilla', 'Homna'),
('Cumilla', 'Comilla Sadar'),
('Cumilla', 'Laksam'),
('Cumilla', 'Monohorgonj'),
('Cumilla', 'Meghna'),
('Cumilla', 'Muradnagar'),
('Cumilla', 'Nangalkot'),
('Cumilla', 'Comilla Sadar South'),
('Cumilla', 'Titas'),
('Cox''s Bazar', 'Chakaria'),
('Cox''s Bazar', '{{198}}''''{{199}}'),
('Cox''s Bazar', 'Kutubdia'),
('Cox''s Bazar', 'Maheshkhali'),
('Cox''s Bazar', 'Ramu'),
('Cox''s Bazar', 'Teknaf'),
('Cox''s Bazar', 'Ukhia'),
('Cox''s Bazar', 'Pekua'),
('Feni', 'Feni Sadar'),
('Feni', 'Chagalnaiya'),
('Feni', 'Daganbhyan'),
('Feni', 'Parshuram'),
('Feni', 'Fhulgazi'),
('Feni', 'Sonagazi'),
('Khagrachari', 'Dighinala'),
('Khagrachari', 'Khagrachhari'),
('Khagrachari', 'Lakshmichhari'),
('Khagrachari', 'Mahalchhari'),
('Khagrachari', 'Manikchhari'),
('Khagrachari', 'Matiranga'),
('Khagrachari', 'Panchhari'),
('Khagrachari', 'Ramgarh'),
('Lakshmipur', 'Lakshmipur Sadar'),
('Lakshmipur', 'Raipur'),
('Lakshmipur', 'Ramganj'),
('Lakshmipur', 'Ramgati'),
('Lakshmipur', 'Komol Nagar'),
('Noakhali', 'Noakhali Sadar'),
('Noakhali', 'Begumganj'),
('Noakhali', 'Chatkhil'),
('Noakhali', 'Companyganj'),
('Noakhali', 'Shenbag'),
('Noakhali', 'Hatia'),
('Noakhali', 'Kobirhat'),
('Noakhali', 'Sonaimuri'),
('Noakhali', 'Suborno Char'),
('Rangamati', 'Rangamati Sadar'),
('Rangamati', 'Belaichhari'),
('Rangamati', 'Bagaichhari'),
('Rangamati', 'Barkal'),
('Rangamati', 'Juraichhari'),
('Rangamati', 'Rajasthali'),
('Rangamati', 'Kaptai'),
('Rangamati', 'Langadu'),
('Rangamati', 'Nannerchar'),
('Rangamati', 'Kaukhali'),
('Dhaka', 'Dhamrai'),
('Dhaka', 'Dohar'),
('Dhaka', 'Keraniganj'),
('Dhaka', 'Nawabganj'),
('Dhaka', 'Savar'),
('Faridpur', 'Faridpur Sadar'),
('Faridpur', 'Boalmari'),
('Faridpur', 'Alfadanga'),
('Faridpur', 'Madhukhali'),
('Faridpur', 'Bhanga'),
('Faridpur', 'Nagarkanda'),
('Faridpur', 'Charbhadrasan'),
('Faridpur', 'Sadarpur'),
('Faridpur', 'Shaltha'),
('Gazipur', 'Gazipur Sadar-Joydebpur'),
('Gazipur', 'Kaliakior'),
('Gazipur', 'Kapasia'),
('Gazipur', 'Sripur'),
('Gazipur', 'Kaliganj'),
('Gazipur', 'Tongi'),
('Gopalganj', 'Gopalganj Sadar'),
('Gopalganj', 'Kashiani'),
('Gopalganj', 'Kotalipara'),
('Gopalganj', 'Muksudpur'),
('Gopalganj', 'Tungipara'),
('Jamalpur', 'Dewanganj'),
('Jamalpur', 'Baksiganj'),
('Jamalpur', 'Islampur'),
('Jamalpur', 'Jamalpur Sadar'),
('Jamalpur', 'Madarganj'),
('Jamalpur', 'Melandaha'),
('Jamalpur', 'Sarishabari'),
('Jamalpur', 'Narundi Police I.C'),
('Kishoreganj', 'Astagram'),
('Kishoreganj', 'Bajitpur'),
('Kishoreganj', 'Bhairab'),
('Kishoreganj', 'Hossainpur'),
('Kishoreganj', 'Itna'),
('Kishoreganj', 'Karimganj'),
('Kishoreganj', 'Katiadi'),
('Kishoreganj', 'Kishoreganj Sadar'),
('Kishoreganj', 'Kuliarchar'),
('Kishoreganj', 'Mithamain'),
('Kishoreganj', 'Nikli'),
('Kishoreganj', 'Pakundia'),
('Kishoreganj', 'Tarail'),
('Madaripur', 'Madaripur Sadar'),
('Madaripur', 'Kalkini'),
('Madaripur', 'Rajoir'),
('Madaripur', 'Shibchar'),
('Manikganj', 'Manikganj Sadar'),
('Manikganj', 'Singair'),
('Manikganj', 'Shibalaya'),
('Manikganj', 'Saturia'),
('Manikganj', 'Harirampur'),
('Manikganj', 'Ghior'),
('Manikganj', 'Daulatpur'),
('Munshiganj', 'Lohajang'),
('Munshiganj', 'Sreenagar'),
('Munshiganj', 'Munshiganj Sadar'),
('Munshiganj', 'Sirajdikhan'),
('Munshiganj', 'Tongibari'),
('Munshiganj', 'Gazaria'),
('Mymensingh', 'Bhaluka'),
('Mymensingh', 'Trishal'),
('Mymensingh', 'Haluaghat'),
('Mymensingh', 'Muktagachha'),
('Mymensingh', 'Dhobaura'),
('Mymensingh', 'Fulbaria'),
('Mymensingh', 'Gaffargaon'),
('Mymensingh', 'Gauripur'),
('Mymensingh', 'Ishwarganj'),
('Mymensingh', 'Mymensingh Sadar'),
('Mymensingh', 'Nandail'),
('Mymensingh', 'Phulpur'),
('Narayanganj', 'Araihazar'),
('Narayanganj', 'Sonargaon'),
('Narayanganj', 'Bandar'),
('Narayanganj', 'Naryanganj Sadar'),
('Narayanganj', 'Rupganj'),
('Narayanganj', 'Siddirgonj'),
('Narsingdi', 'Belabo'),
('Narsingdi', 'Monohardi'),
('Narsingdi', 'Narsingdi Sadar'),
('Narsingdi', 'Palash'),
('Narsingdi', 'Raipura'),
('Narsingdi', 'Shibpur'),
('Netrokona', 'Kendua Upazilla'),
('Netrokona', 'Atpara Upazilla'),
('Netrokona', 'Barhatta Upazilla'),
('Netrokona', 'Durgapur Upazilla'),
('Netrokona', 'Kalmakanda Upazilla'),
('Netrokona', 'Madan Upazilla'),
('Netrokona', 'Mohanganj Upazilla'),
('Netrokona', 'Netrakona-S Upazilla'),
('Netrokona', 'Purbadhala Upazilla'),
('Netrokona', 'Khaliajuri Upazilla'),
('Rajbari', 'Baliakandi'),
('Rajbari', 'Goalandaghat'),
('Rajbari', 'Pangsha'),
('Rajbari', 'Kalukhali'),
('Rajbari', 'Rajbari Sadar'),
('Shariatpur', 'Shariatpur Sadar -Palong'),
('Shariatpur', 'Damudya'),
('Shariatpur', 'Naria'),
('Shariatpur', 'Jajira'),
('Shariatpur', 'Bhedarganj'),
('Shariatpur', 'Gosairhat'),
('Sherpur', 'Jhenaigati'),
('Sherpur', 'Nakla'),
('Sherpur', 'Nalitabari'),
('Sherpur', 'Sherpur Sadar'),
('Sherpur', 'Sreebardi'),
('Tangail', 'Tangail Sadar'),
('Tangail', 'Sakhipur'),
('Tangail', 'Basail'),
('Tangail', 'Madhupur'),
('Tangail', 'Ghatail'),
('Tangail', 'Kalihati'),
('Tangail', 'Nagarpur'),
('Tangail', 'Mirzapur'),
('Tangail', 'Gopalpur'),
('Tangail', 'Delduar'),
('Tangail', 'Bhuapur'),
('Tangail', 'Dhanbari'),
('Bagerhat', 'Bagerhat Sadar'),
('Bagerhat', 'Chitalmari'),
('Bagerhat', 'Fakirhat'),
('Bagerhat', 'Kachua'),
('Bagerhat', 'Mollahat'),
('Bagerhat', 'Mongla'),
('Bagerhat', 'Morrelganj'),
('Bagerhat', 'Rampal'),
('Bagerhat', 'Sarankhola'),
('Chuadanga', 'Damurhuda'),
('Chuadanga', 'Chuadanga-S'),
('Chuadanga', 'Jibannagar'),
('Chuadanga', 'Alamdanga'),
('Jashore', 'Abhaynagar'),
('Jashore', 'Keshabpur'),
('Jashore', 'Bagherpara'),
('Jashore', 'Jessore Sadar'),
('Jashore', 'Chaugachha'),
('Jashore', 'Manirampur'),
('Jashore', 'Jhikargachha'),
('Jashore', 'Sharsha'),
('Jhenaidah', 'Jhenaidah Sadar'),
('Jhenaidah', 'Maheshpur'),
('Jhenaidah', 'Kaliganj'),
('Jhenaidah', 'Kotchandpur'),
('Jhenaidah', 'Shailkupa'),
('Jhenaidah', 'Harinakunda'),
('Khulna', 'Terokhada'),
('Khulna', 'Batiaghata'),
('Khulna', 'Dacope'),
('Khulna', 'Dumuria'),
('Khulna', 'Dighalia'),
('Khulna', 'Koyra'),
('Khulna', 'Paikgachha'),
('Khulna', 'Phultala'),
('Khulna', 'Rupsa'),
('Kushtia', 'Kushtia Sadar'),
('Kushtia', 'Kumarkhali'),
('Kushtia', 'Daulatpur'),
('Kushtia', 'Mirpur'),
('Kushtia', 'Bheramara'),
('Kushtia', 'Khoksa'),
('Magura', 'Magura Sadar'),
('Magura', 'Mohammadpur'),
('Magura', 'Shalikha'),
('Magura', 'Sreepur'),
('Meherpur', 'angni'),
('Meherpur', 'Mujib Nagar'),
('Meherpur', 'Meherpur-S'),
('Narail', 'Narail-S Upazilla'),
('Narail', 'Lohagara Upazilla'),
('Narail', 'Kalia Upazilla'),
('Satkhira', 'Satkhira Sadar'),
('Satkhira', 'Assasuni'),
('Satkhira', 'Debhata'),
('Satkhira', 'Tala'),
('Satkhira', 'Kalaroa'),
('Satkhira', 'Kaliganj'),
('Satkhira', 'Shyamnagar'),
('Bogura', 'Adamdighi'),
('Bogura', 'Bogra Sadar'),
('Bogura', 'Sherpur'),
('Bogura', 'Dhunat'),
('Bogura', 'Dhupchanchia'),
('Bogura', 'Gabtali'),
('Bogura', 'Kahaloo'),
('Bogura', 'Nandigram'),
('Bogura', 'Sahajanpur'),
('Bogura', 'Sariakandi'),
('Bogura', 'Shibganj'),
('Bogura', 'Sonatala'),
('Joypurhat', 'Joypurhat S'),
('Joypurhat', 'Akkelpur'),
('Joypurhat', 'Kalai'),
('Joypurhat', 'Khetlal'),
('Joypurhat', 'Panchbibi'),
('Naogaon', 'Naogaon Sadar'),
('Naogaon', 'Mohadevpur'),
('Naogaon', 'Manda'),
('Naogaon', 'Niamatpur'),
('Naogaon', 'Atrai'),
('Naogaon', 'Raninagar'),
('Naogaon', 'Patnitala'),
('Naogaon', 'Dhamoirhat'),
('Naogaon', 'Sapahar'),
('Naogaon', 'Porsha'),
('Naogaon', 'Badalgachhi'),
('Natore', 'Natore Sadar'),
('Natore', 'Baraigram'),
('Natore', 'Bagatipara'),
('Natore', 'Lalpur'),
('Nawabganj', 'Bholahat'),
('Nawabganj', 'Gomastapur'),
('Nawabganj', 'Nachole'),
('Nawabganj', 'Nawabganj Sadar'),
('Nawabganj', 'Shibganj'),
('Pabna', 'Atgharia'),
('Pabna', 'Bera'),
('Pabna', 'Bhangura'),
('Pabna', 'Chatmohar'),
('Pabna', 'Faridpur'),
('Pabna', 'Ishwardi'),
('Pabna', 'Pabna Sadar'),
('Pabna', 'Santhia'),
('Pabna', 'Sujanagar'),
('Rajshahi', 'Bagha'),
('Rajshahi', 'Bagmara'),
('Rajshahi', 'Charghat'),
('Rajshahi', 'Durgapur'),
('Rajshahi', 'Godagari'),
('Rajshahi', 'Mohanpur'),
('Rajshahi', 'Paba'),
('Rajshahi', 'Puthia'),
('Rajshahi', 'Tanore'),
('Sirajgonj', 'Sirajganj Sadar'),
('Sirajgonj', 'Belkuchi'),
('Sirajgonj', 'Chauhali'),
('Sirajgonj', 'Kamarkhanda'),
('Sirajgonj', 'Kazipur'),
('Sirajgonj', 'Raiganj'),
('Sirajgonj', 'Shahjadpur'),
('Sirajgonj', 'Tarash'),
('Sirajgonj', 'Ullahpara'),
('Dinajpur', 'Birampur'),
('Dinajpur', 'Birganj'),
('Dinajpur', 'Biral'),
('Dinajpur', 'Bochaganj'),
('Dinajpur', 'Chirirbandar'),
('Dinajpur', 'Phulbari'),
('Dinajpur', 'Ghoraghat'),
('Dinajpur', 'Hakimpur'),
('Dinajpur', 'Kaharole'),
('Dinajpur', 'Khansama'),
('Dinajpur', 'Dinajpur Sadar'),
('Dinajpur', 'Nawabganj'),
('Dinajpur', 'Parbatipur'),
('Gaibandha', 'Fulchhari'),
('Gaibandha', 'Gaibandha sadar'),
('Gaibandha', 'Gobindaganj'),
('Gaibandha', 'Palashbari'),
('Gaibandha', 'Sadullapur'),
('Gaibandha', 'Saghata'),
('Gaibandha', 'Sundarganj'),
('Kurigram', 'Kurigram Sadar'),
('Kurigram', 'Nageshwari'),
('Kurigram', 'Bhurungamari'),
('Kurigram', 'Phulbari'),
('Kurigram', 'Rajarhat'),
('Kurigram', 'Ulipur'),
('Kurigram', 'Chilmari'),
('Kurigram', 'Rowmari'),
('Kurigram', 'Char Rajibpur'),
('Lalmonirhat', 'Lalmanirhat Sadar'),
('Lalmonirhat', 'Aditmari'),
('Lalmonirhat', 'Kaliganj'),
('Lalmonirhat', 'Hatibandha'),
('Lalmonirhat', 'Patgram'),
('Nilphamari', 'Nilphamari Sadar'),
('Nilphamari', 'Saidpur'),
('Nilphamari', 'Jaldhaka'),
('Nilphamari', 'Kishoreganj'),
('Nilphamari', 'Domar'),
('Nilphamari', 'Dimla'),
('Panchagarh', 'Panchagarh Sadar'),
('Panchagarh', 'Debiganj'),
('Panchagarh', 'Boda'),
('Panchagarh', 'Atwari'),
('Panchagarh', 'Tetulia'),
('Rangpur', 'Badarganj'),
('Rangpur', 'Mithapukur'),
('Rangpur', 'Gangachara'),
('Rangpur', 'Kaunia'),
('Rangpur', 'Rangpur Sadar'),
('Rangpur', 'Pirgachha'),
('Rangpur', 'Pirganj'),
('Rangpur', 'Taraganj'),
('Thakurgaon', 'Thakurgaon Sadar'),
('Thakurgaon', 'Pirganj'),
('Thakurgaon', 'Baliadangi'),
('Thakurgaon', 'Haripur'),
('Thakurgaon', 'Ranisankail'),
('Habiganj', 'Ajmiriganj'),
('Habiganj', 'Baniachang'),
('Habiganj', 'Bahubal'),
('Habiganj', 'Chunarughat'),
('Habiganj', 'Habiganj Sadar'),
('Habiganj', 'Lakhai'),
('Habiganj', 'Madhabpur'),
('Habiganj', 'Nabiganj'),
('Habiganj', 'Shaistagonj'),
('Maulvibazar', 'Moulvibazar Sadar'),
('Maulvibazar', 'Barlekha'),
('Maulvibazar', 'Juri'),
('Maulvibazar', 'Kamalganj'),
('Maulvibazar', 'Kulaura'),
('Maulvibazar', 'Rajnagar'),
('Maulvibazar', 'Sreemangal'),
('Sunamganj', 'Bishwamvarpur'),
('Sunamganj', 'Chhatak'),
('Sunamganj', 'Derai'),
('Sunamganj', 'Dharampasha'),
('Sunamganj', 'Dowarabazar'),
('Sunamganj', 'Jagannathpur'),
('Sunamganj', 'Jamalganj'),
('Sunamganj', 'Sulla'),
('Sunamganj', 'Sunamganj Sadar'),
('Sunamganj', 'Shanthiganj'),
('Sunamganj', 'Tahirpur'),
('Sylhet', 'Sylhet Sadar'),
('Sylhet', 'Beanibazar'),
('Sylhet', 'Bishwanath'),
('Sylhet', 'Dakshin Surma'),
('Sylhet', 'Balaganj'),
('Sylhet', 'Companiganj'),
('Sylhet', 'Fenchuganj'),
('Sylhet', 'Golapganj'),
('Sylhet', 'Gowainghat'),
('Sylhet', 'Jointapur'),
('Sylhet', 'Kanaighat'),
('Sylhet', 'Zakiganj'),
('Sylhet', 'Nobigonj'),
('Cox''s Bazar', 'Eidgaon'),
('Sunamganj', 'Modhyanagar'),
('Madaripur', 'Dasar'),
('Dhaka', 'Gulshan'),
('Dhaka', 'Banani'),
('Dhaka', 'Baridhara'),
('Dhaka', 'Uttara'),
('Dhaka', 'Mirpur'),
('Dhaka', 'Mohakhali'),
('Dhaka', 'Niketon'),
('Dhaka', 'Khilkhet'),
('Dhaka', 'Badda'),
('Dhaka', 'Cantonment'),
('Dhaka', 'Kuril'),
('Dhaka', 'Vatara'),
('Dhaka', 'Adabor'),
('Dhaka', 'Shewrapara'),
('Dhaka', 'Agargaon'),
('Dhaka', 'Kazipara'),
('Dhaka', 'Darussalam'),
('Dhaka', 'Kafrul'),
('Dhaka', 'Uttarkhan'),
('Dhaka', 'Pallabi'),
('Dhaka', 'Nikunja'),
('Dhaka', 'Bashundhara R/A'),
('Dhaka', 'Tongi'),
('Dhaka', 'Kakrail'),
('Dhaka', 'Shyamoli'),
('Dhaka', 'Mohakhali DOHS'),
('Dhaka', 'Rampura'),
('Dhaka', 'Mirpur DOHS'),
('Dhaka', 'Mirpur Cantonment'),
('Dhaka', 'Shah Ali'),
('Dhaka', 'Rayer Bazar'),
('Dhaka', 'Farmgate'),
('Dhaka', 'Kamalapur'),
('Dhaka', 'Elephant Road'),
('Dhaka', 'Lalmatia'),
('Dhaka', 'Malibagh'),
('Dhaka', 'Tejgaon'),
('Dhaka', 'Sher-e-Bangla Nagar'),
('Dhaka', 'Gabtoli'),
('Dhaka', 'Rupnagar'),
('Dhaka', 'Dhanmondi'),
('Dhaka', 'Mohammadpur'),
('Dhaka', 'Lalbagh'),
('Dhaka', 'Kotwali'),
('Dhaka', 'Shahbag'),
('Dhaka', 'Armanitola'),
('Dhaka', 'Shyampur'),
('Dhaka', 'Demra'),
('Dhaka', 'Laxmibazar'),
('Dhaka', 'Gendaria'),
('Dhaka', 'Wari'),
('Dhaka', 'Sutrapur'),
('Dhaka', 'Kamrangirchar'),
('Dhaka', 'Kotwali Police Line'),
('Dhaka', 'Bangshal'),
('Dhaka', 'Chawkbazar'),
('Dhaka', 'Nayabazar'),
('Dhaka', 'Nababganj'),
('Dhaka', 'Banglamotor'),
('Dhaka', 'Fakirapool'),
('Dhaka', 'Shantinagar'),
('Dhaka', 'Moghbazar'),
('Dhaka', 'Gulshan Model Town'),
('Dhaka', 'Bashundhara'),
('Dhaka', 'Mouchak'),
('Dhaka', 'Siddheshwari'),
('Dhaka', 'Jatrabari'),
('Dhaka', 'Jurain'),
('Dhaka', 'Dholpur'),
('Dhaka', 'Posta'),
('Dhaka', 'Dhaka Cantonment'),
('Dhaka', 'Uttar Khan'),
('Dhaka', 'Darus Salam'),
('Dhaka', 'Airport'),
('Dhaka', 'Rampura Bazar'),
('Dhaka', 'Middle Badda'),
('Dhaka', 'Banasree Block-C'),
('Dhaka', 'North Badda'),
('Dhaka', 'Postogola'),
('Dhaka', 'Dakshinkhan'),
('Dhaka', 'Jhigatola'),
('Dhaka', 'Pallabi Extension'),
('Dhaka', 'Basabo'),
('Dhaka', 'Merul Badda'),
('Dhaka', 'Bashabo'),
('Dhaka', 'Shantibagh'),
('Dhaka', 'Basundhara Residential Area'),
('Dhaka', 'Mohammadpur Housing'),
('Dhaka', 'Green Road'),
('Dhaka', 'Mohammadpur Krishi Market'),
('Dhaka', 'Tikatuli'),
('Dhaka', 'Basundhara R/A'),
('Dhaka', 'Shantibagh R/A'),
('Dhaka', 'Monipur'),
('Dhaka', 'Baily Road'),
('Dhaka', 'New Market'),
('Dhaka', 'Hatirpool'),
('Dhaka', 'Panthapath'),
('Dhaka', 'Zigatola'),
('Dhaka', 'Badda Link Road'),
('Dhaka', 'South Mugda'),
('Dhaka', 'Notun Bazar'),
('Dhaka', 'Malibagh Chowdhurypara'),
('Dhaka', 'Kadamtoli'),
('Dhaka', 'Khilgaon'),
('Dhaka', 'Shampur'),
('Dhaka', 'Malibagh Rail Gate'),
('Dhaka', 'Bongshal'),
('Dhaka', 'Motijheel'),
('Dhaka', 'Tanti Bazar'),
('Dhaka', 'Nayatola'),
('Dhaka', 'Khilgaon Taltola'),
('Dhaka', 'Bijoynagar'),
('Dhaka', 'Islampur'),
('Dhaka', 'Kalabagan'),
('Dhaka', 'Mirpur-1'),
('Dhaka', 'Mirpur-2'),
('Dhaka', 'Mirpur-6'),
('Dhaka', 'Mirpur-7'),
('Dhaka', 'Mirpur-10'),
('Dhaka', 'Mirpur-11'),
('Dhaka', 'Mirpur-12'),
('Dhaka', 'Mirpur-13'),
('Dhaka', 'Mirpur-14')
ON CONFLICT (district, area) DO NOTHING;